collections:
  - name: community.general
  - name: community.hashi_vault
  - name: community.docker
  - name: amazon.aws
  - name: community.aws
roles:
  - name: incus-windows
    src: https://github.com/BeryJu/ansible-role-incus-windows
    version: 9bd8723b0813a3fd70c1cbfb5961d3350089808e
