collections:
  - name: community.general
  - name: community.hashi_vault
  - name: community.docker
  - name: amazon.aws
  - name: community.aws
roles:
  - name: incus-windows
    src: https://github.com/BeryJu/ansible-role-incus-windows
    version: 1616978df7f1a8184bbcc2dad868f9c763ce7c13
