collections:
  - name: community.general
  - name: community.hashi_vault
  - name: community.docker
  - name: amazon.aws
  - name: community.aws
roles:
  - name: incus-windows
    src: https://github.com/BeryJu/ansible-role-incus-windows
    version: cd923a37a114e2635877f1671d1d0b6c722c43f9
