- name: Copy check_mk Agent
  copy:
    src: "files/{{ cmk_agent_file }}"
    dest: /var/tmp
    owner: root
    group: root
    mode: 0775
- name: Install extra packages
  apt:
    name: "{{ cmk_extra_packages }}"
  notify:
    - Reconfigure package on change
    - Clean systemd-failed
- name: Install check_mk Agent
  apt:
    deb: "/var/tmp/{{ cmk_agent_file }}"
    state: present
    force: yes
  notify:
    - Reconfigure package on change
    - Clean systemd-failed
- name: Configure encryption
  template:
    dest: "/etc/check_mk/encryption.cfg"
    src: templates/encryption.cfg
    owner: root
    group: root
    mode: 0640
- name: run handlers
  meta: flush_handlers
- name: Install Plugins
  copy:
    src: "files/plugins/{{ item }}"
    dest: "/usr/lib/check_mk_agent/plugins/{{ item }}"
    owner: root
    group: root
    mode: '0770'
  loop: "{{ cmk_plugins }}"
- name: Remove Plugins
  file:
    path: "/usr/lib/check_mk_agent/plugins/{{ item }}"
    state: absent
  loop: "{{ cmk_plugins_absent }}"
