- name: generate newaliases
  command: newaliases

- name: restart postfix
  service:
    name: postfix
    state: restarted

- name: generate relay_passwd
  command: postmap hash:/etc/postfix/relay_passwd
