version: "3"

networks:
  blocky:
    ipam:
      config:
        - subnet: 100.64.0.0/24
          gateway: 100.64.0.1

services:
  blocky:
    image: spx01/blocky
    container_name: blocky
    restart: unless-stopped
    networks:
      adguard:
        ipv4_address: 100.64.0.53
    ports:
      - "4000:4000/tcp"
    volumes:
      - ./config.yml:/app/config.yml
