- name: docker-compose | python modules
  pip:
    name:
      - docker
      - "docker-compose=={{ docker_compose_version }}"
    extra_args: -U
  when: "docker_compose is defined"
- name: docker-compose | download
  get_url:
    url: "https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-Linux-x86_64"
    dest: /usr/local/bin/docker-compose
    # checksum: "sha256:https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-Linux-x86_64.sha256"
    mode: '0755'
  when: "docker_compose is defined"
