- name: sysctl | set flags
  ansible.posix.sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
  loop:
    - key: net.bridge.bridge-nf-call-ip6tables
      value: 1
    - key: net.bridge.bridge-nf-call-iptables
      value: 1
    - key: net.ipv4.ip_forward
      value: 1
    - key: fs.inotify.max_user_watches
      value: 100000
    - key: fs.inotify.max_user_instances
      value: 100000
