all:
  hosts:
    optiplex-3090-bq1plp3.prod.beryju.io:
    sentry1.prod.beryju.io:
    kube-api.beryjuio-oci.k8s.beryju.io:

kube:
  hosts:
    optiplex-3090-bq1plp3.prod.beryju.io:
      beryjuio_kube_cluster_name: beryjuio-home
      beryjuio_kube_version: v1.34
      beryjuio_kube_arch: linux/amd64
    kube-api.beryjuio-oci.k8s.beryju.io:
      beryjuio_kube_cluster_name: beryjuio-oci
      beryjuio_kube_version: v1.34
      beryjuio_kube_arch: linux/arm64/v8
