all:
  hosts:
    optiplex-3090-bq1plp3.lab.beryju.org:
    sentry1.prod.beryju.io:
    kube-api.beryjuio-oci.k8s.beryju.io:

kubeadm:
  hosts:
    optiplex-3090-bq1plp3.lab.beryju.org:
    kube-api.beryjuio-oci.k8s.beryju.io:
