all:
  hosts:
    hass1.prod.beryju.org:

storage:
  children:
    nfs_server:
      hosts:
        nas1.prod.beryju.org:
  hosts:
    backup-s3.prod.beryju.org:

media:
  hosts:
    plex1.prod.beryju.org:

docker:
  hosts:
    ak-dev-k3s1.lab.beryju.org:
    k8s-defr-c1.lab.beryju.org:
    k8s-defr-w3.lab.beryju.org:
    k8s-defr-w4.lab.beryju.org:
    k8s-defr-w5.lab.beryju.org:
    k8s-prd-c1.prod.beryju.org:
    k8s-prd-w1.prod.beryju.org:
    k8s-prd-w2.prod.beryju.org:
    k8s-prd-w3.prod.beryju.org:
    k8s-prd-w4.prod.beryju.org:
    # k8s-prd-w5.prod.beryju.org:
    mon1.prod.beryju.org:
  children:
    compose:
      hosts:
        ak-dev-dc1.lab.beryju.org:
        analytics1.prod.beryju.org:
        dev1.lab.beryju.org:
        gitlab1.prod.beryju.org:
        mc1.prod.beryju.org:
        netbox1.prod.beryju.org:
        plex1.prod.beryju.org:
        rancher1.prod.beryju.org:
        sentry1.prod.beryju.org:
        unifi1.prod.beryju.org:
        vault1.prod.beryju.org:
