[tool.poetry]
name = "infrastructure"
version = "0.1.0"
description = ""
authors = ["Jens Langhammer <jens.langhammer@beryju.org>"]
license = "GPL"

[tool.poetry.dependencies]
python = "^3.8"
hvac = "^1.0.2"
ansible = "^7.0.0"
python-gitlab = "^3.12.0"
python-dateutil = "^2.8.2"
pytz = "^2022.6"
passlib = "^1.7.4"
bcrypt = "^4.0.1"
ara = "^1.6.0"

[tool.poetry.dev-dependencies]
ansible-lint = "<7"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
