[tool.poetry]
name = "infrastructure"
version = "0.1.0"
description = ""
authors = ["Jens Langhammer <jens.langhammer@beryju.org>"]
license = "GPL"

[tool.poetry.dependencies]
python = "^3.10"
hvac = "^0.11.2"
ansible = "^5.2.0"
python-gitlab = "^3.1.0"
python-dateutil = "^2.8.2"
pytz = "^2021.3"
passlib = "^1.7.4"
bcrypt = "^3.2.0"

[tool.poetry.dev-dependencies]
ansible-lint = "<6"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
