[tool.poetry]
name = "infrastructure"
version = "0.1.0"
description = ""
authors = ["Jens Langhammer <jens.langhammer@beryju.org>"]
license = "GPL"

[tool.poetry.dependencies]
python = "^3.11"
ansible = "*"
ansible-lint = "*"
ara = "*"
bcrypt = "*"
hvac = "*"
passlib = "*"
python-dateutil = "*"
python-gitlab = "*"
pytz = "*"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
