# since hass1.prod.beryju.org is "faked" to debian for supervisor
# we can't use the role
- hosts: all:!hass1.prod.beryju.org
  become: true
  roles:
    - beryjuorg-apt

- hosts: all
  become: true
  roles:
    - beryjuorg-common
    - beryjuorg-cmk

- hosts: all:!backup-s3.beryju.org
  become: true
  roles:
    - beryjuorg-syslog

- hosts: storage
  become: true
  roles:
    - beryjuorg-veeam-box

- hosts: nfs_server
  become: true
  roles:
    - beryjuorg-nfs-server

- hosts: docker
  become: true
  roles:
    - beryjuorg-docker

- hosts: compose
  become: true
  tasks:
    - name: docker-compose | stacks
      include_role:
        name: beryjuorg-docker-stacks
      vars:
        stack: "{{ item }}"
      with_items: "{{ compose_stacks }}"

- hosts: media
  become: true
  tasks:
    - name: NFS | common
      apt:
        pkg: nfs-common
    - name: Plex | create /plex-transcode dir
      file:
        state: directory
        path: /plex-transcode
        owner: '1000'
        group: '1000'
    - name: Plex | Mount Media
      mount:
        state: mounted
        fstype: nfs
        src: "nas1.prod.beryju.org:/bigpool/media"
        path: /media
        opts: soft,intr,rsize=32768,wsize=32768
