# since hass1.prod.beryju.org is "faked" to debian for supervisor
# we can't use the role
- hosts: all:!hass1.prod.beryju.org
  become: true
  roles:
    - beryjuorg_apt

- hosts: all
  become: true
  roles:
    - beryjuorg_common
    - beryjuorg_node_exporter
    - beryjuorg_mta

- hosts: all:!backup-s3.beryju.org
  become: true
  roles:
    - beryjuorg_syslog

- hosts: storage
  become: true
  roles:
    - beryjuorg_veeam_box

- hosts: nfs_server
  become: true
  roles:
    - beryjuorg_nfs_server

- hosts: docker
  become: true
  roles:
    - beryjuorg_docker

- hosts: compose
  become: true
  tasks:
    - name: docker-compose | stacks
      include_role:
        name: beryjuorg_docker_stacks
      vars:
        stack: "{{ item }}"
      with_items: "{{ compose_stacks }}"

- hosts: media
  become: true
  tasks:
    - name: NFS | common
      apt:
        pkg: nfs-common
      register: apt_res
      retries: 5
      until: apt_res is success
    - name: Plex | create /plex-transcode dir
      file:
        state: directory
        path: /plex-transcode
        owner: '1000'
        group: '1000'
        mode: 0755
    - name: Plex | Mount Media
      mount:
        state: mounted
        fstype: nfs
        src: "nas1.prod.beryju.org:/bigpool/media"
        path: /media
        opts: soft,intr,rsize=32768,wsize=32768
