- import_playbook: ./bootstrap.yaml
- hosts: all
  become: true
  roles:
    - beryjuio_common
    - beryjuio_mta
    - beryjuio_ak
    - beryjuio_containerd
- hosts: kube
  become: true
  tags:
    - kube
  roles:
    - beryjuio_kube
- hosts: standalone
  become: true
  tags:
    - standalone
  roles:
    - beryjuio_monitoring
