version: "3.7"
services:
  vault:
    image: hashicorp/vault:1.10.0
    ports:
      - "10.120.0.69:8200:8200"
      - "10.120.0.69:9443:9443"
    volumes:
      - /srv/vault/data:/vault/data:rw
      - /srv/vault/files:/vault/file:rw
      - /srv/vault/config:/vault/config:rw
      - /etc/puppetlabs/puppet/ssl/:/etc/puppetlabs/puppet/ssl/
    cap_add:
      - IPC_LOCK
    entrypoint: vault server -config=/vault/config/vault.hcl
