apiVersion: kubeadm.k8s.io/v1beta4
kind: ClusterConfiguration
apiServer:
  certSANs:
    - kube-api.{{ beryjuio_kube_cluster_name }}.k8s.beryju.io
  extraArgs:
    - name: authorization-mode
      value: Node,RBAC
    - name: logging-format
      value: json
    - name: oidc-client-id
      value: k8s-cluster-{{ beryjuio_kube_cluster_name }}
    - name: oidc-groups-claim
      value: groups
    - name: oidc-groups-prefix
      value: "oidc:"
    - name: oidc-issuer-url
      value: https://id.beryju.io/application/o/k8s-{{ beryjuio_kube_cluster_name }}/
    - name: oidc-username-claim
      value: email
caCertificateValidityPeriod: 87600h0m0s
certificateValidityPeriod: 8760h0m0s
certificatesDir: /etc/kubernetes/pki
clusterName: kubernetes
controlPlaneEndpoint: kube-api.{{ beryjuio_kube_cluster_name }}.k8s.beryju.io:6443
controllerManager:
  extraArgs:
    - name: bind-address
      value: 0.0.0.0
    - name: logging-format
      value: json
dns: {}
encryptionAlgorithm: RSA-2048
etcd:
  local:
    dataDir: /var/lib/etcd
    extraArgs:
      - name: listen-metrics-urls
        value: http://0.0.0.0:2381
imageRepository: registry.k8s.io
kubernetesVersion: "latest"
networking:
  dnsDomain: cluster.local
  podSubnet: 10.244.0.0/16
  serviceSubnet: 10.96.0.0/12
proxy: {}
scheduler:
  extraArgs:
    - name: bind-address
      value: 0.0.0.0
    - name: logging-format
      value: json
---
apiVersion: kubeadm.k8s.io/v1beta4
apply:
  certificateRenewal: true
  etcdUpgrade: true
  imagePullPolicy: IfNotPresent
  imagePullSerial: true
diff: {}
kind: UpgradeConfiguration
node:
  certificateRenewal: true
  etcdUpgrade: true
  imagePullPolicy: IfNotPresent
  imagePullSerial: true
plan:
  etcdUpgrade: true
timeouts:
  controlPlaneComponentHealthCheck: 4m0s
  discovery: 5m0s
  etcdAPICall: 2m0s
  kubeletHealthCheck: 4m0s
  kubernetesAPICall: 1m0s
  tlsBootstrap: 5m0s
  upgradeManifests: 5m0s
