name: 'Run ansible-playbook'
description: 'Run an ansible playbook'
inputs:
  playbook:
    description: 'The playbook'
    required: true

runs:
  using: "composite"
  steps:
    - name: Install poetry
      shell: bash
      run: pipx install poetry || true
    - uses: actions/setup-python@v6
      with:
        python-version: '3.13'
    - name: prepare
      shell: bash
      run: |
        python3 -m pip install -U wheel poetry
        poetry env use python3.13
        poetry install
        # Ensure jq is installed
        sudo apt update
        sudo apt install -y jq openssh-client
    - name: Get GitHub JWT
      id: jwt
      shell: bash
      run: |
        JWT=$(curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL" | jq -r .value)
        echo "token=${JWT}" >> $GITHUB_OUTPUT
    - name: run job
      shell: bash
      env:
        ANSIBLE_REMOTE_USER: ansible
        ANSIBLE_PRIVATE_KEY_FILE: ./ansible.key
        ANSIBLE_HOST_KEY_CHECKING: "false"
        ANSIBLE_HASHI_VAULT_ADDR: https://vault.beryju.io
        ANSIBLE_HASHI_VAULT_AUTH_METHOD: jwt
        ANSIBLE_HASHI_VAULT_MOUNT_POINT: github-actions
        ANSIBLE_HASHI_VAULT_JWT: ${{ steps.jwt.outputs.token }}
        ANSIBLE_HASHI_VAULT_ROLE_ID: github-terraform
        ARA_API_CLIENT: http
        ARA_API_SERVER: "https://ara.beryjuio-home.k8s.beryju.io"
      run: |
        export ANSIBLE_CALLBACK_PLUGINS=$(poetry run python3 -m ara.setup.callback_plugins)
        poetry run ansible-playbook -v ${{ inputs.playbook }}
