name: 'Run ansible-playbook'
description: 'Run an ansible playbook'
inputs:
  playbook:
    description: 'The playbook'
    required: true

runs:
  using: "composite"
  steps:
    - name: Install poetry
      shell: bash
      run: pipx install poetry || true
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: prepare
      shell: bash
      run: |
        python3 -m pip install -U wheel poetry
        poetry env use python3.10
        poetry install
        # Ensure jq is installed
        sudo apt install -y jq
    - name: Get GitHub JWT
      id: jwt
      shell: bash
      run: |
        JWT=$(curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL" | jq -r .value)
        echo "::set-output name=token::${JWT}"
    - name: run job
      shell: bash
      env:
        ANSIBLE_REMOTE_USER: ansible
        ANSIBLE_HOST_KEY_CHECKING: "false"
        ANSIBLE_HASHI_VAULT_ADDR: https://vault.beryju.org
        ANSIBLE_HASHI_VAULT_AUTH_METHOD: jwt
        ANSIBLE_HASHI_VAULT_MOUNT_POINT: github-actions
        ANSIBLE_HASHI_VAULT_JWT: ${{ steps.jwt.outputs.token }}
      run: |
        export ANSIBLE_CALLBACK_PLUGINS=$(poetry run python3 -m ara.setup.callback_plugins)
        export ARA_API_CLIENT=http
        export ARA_API_SERVER="http://dev1.lab.beryju.org:4000"
        poetry run ansible-playbook -v ${{ inputs.playbook }}
