name: 'Run ansible-playbook'
description: 'Run an ansible playbook'
inputs:
  playbook:
    description: 'The playbook'
    required: true

runs:
  using: "composite"
  steps:
    - name: Install poetry
      shell: bash
      run: pipx install poetry || true
    - uses: actions/setup-python@v3
      with:
        python-version: '3.10'
        cache: "poetry"
    - name: prepare
      shell: bash
      env:
        INSTALL: ${{ steps.cache-poetry.outputs.cache-hit }}
      run: |
        python3 -m pip install -U wheel poetry
        poetry env use python3.10
        poetry install
        pip install junit_xml
    - name: run job
      shell: bash
      env:
        ANSIBLE_REMOTE_USER: ansible
        ANSIBLE_HOST_KEY_CHECKING: "false"
        ANSIBLE_CALLBACKS_ENABLED: junit
        ANSIBLE_HASHI_VAULT_AUTH_METHOD: cert
        ANSIBLE_HASHI_VAULT_CA_CERT: /etc/puppetlabs/puppet/ssl/certs/ca.pem
        JUNIT_OUTPUT_DIR: tests
      run: |
        export ANSIBLE_HASHI_VAULT_CERT_AUTH_PRIVATE_KEY=/etc/puppetlabs/puppet/ssl/private_keys/$(hostname -f).pem
        export ANSIBLE_HASHI_VAULT_CERT_AUTH_PUBLIC_KEY=/etc/puppetlabs/puppet/ssl/certs/$(hostname -f).pem
        poetry run ansible-playbook --diff -v ${{ inputs.playbook }}
    - if: ${{ always() }}
      uses: codecov/codecov-action@v2
      with:
        directory: tests
        verbose: true
