{
 "title": "BeryJu.io",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "cluster", "label": "Cluster", "query": { "query": "label_values(up, cluster)" } }
  ]
 },
 "panels": [
  { "title": "Alerts", "type": "alertlist", "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 } },
  {
   "title": "Cluster up status",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (cluster) (last_over_time(up{cluster=~\"$cluster\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cluster UP status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum  (last_over_time(up{cluster!=\"\", cluster=~\"$cluster\"}[1m]))",
     "legendFormat": "{{ cluster }}"
    }
   ]
  },
  {
   "title": "Cluster Reconcilers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(\n    count(gotk_resource_info{cluster=~\"$cluster\", customresource_kind=~\"Kustomization|HelmRelease\"})\n    - (count(gotk_resource_info{cluster=~\"$cluster\", customresource_kind=~\"Kustomization|HelmRelease\", ready=\"False\"}) OR on() vector(0))\n)\n+ (\n    count(gotk_resource_info{cluster=~\"$cluster\", customresource_kind=~\"GitRepository|HelmRepository|Bucket|OCIRepository\"})\n    - (count(gotk_resource_info{cluster=~\"$cluster\", customresource_kind=~\"GitRepository|HelmRepository|Bucket|OCIRepository\", ready=\"False\"}) OR on() vector(0))\n)"
    }
   ]
  },
  {
   "title": "Failing Reconcilers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(count(gotk_resource_info{customresource_kind=~\"Kustomization|HelmRelease\", ready=\"False\"}) OR on() vector(0)) +  (count(gotk_resource_info{customresource_kind=~\"GitRepository|HelmRepository|Bucket|OCIRepository\", ready=\"False\"}) OR on() vector(0))"
    }
   ]
  },
  {
   "title": "MetalLB Sessions",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (cluster) (metallb_bgp_session_up{cluster=~\"$cluster\"})",
     "legendFormat": "{{ cluster }}"
    }
   ]
  },
  {
   "title": "BGP connected peers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 22, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "sum(frr_bgp_peer_state) " }
   ]
  },
  {
   "title": "Global CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "sum by (instance) (\n  (1 - sum without (mode) (rate(node_cpu_seconds_total{mode=~\"idle|iowait|steal\", cluster=~\"$cluster\"}[5m])))\n/ ignoring(cpu) group_left\n  count without (cpu, mode) (node_cpu_seconds_total{mode=\"idle\", cluster=~\"$cluster\"})\n)  > 0",
     "legendFormat": "Load avg {{ instance }}"
    }
   ]
  },
  {
   "title": "Global Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 5 },
   "targets": [
    {
     "expr": "(100 -\n(\n  (node_memory_MemAvailable_bytes{cluster=~\"$cluster\"})\n/\n  (node_memory_MemTotal_bytes{cluster=~\"$cluster\"})\n* 100\n))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Global network",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{device=~\"eth.*|enp.*\", cluster=~\"$cluster\"}[$__rate_interval]) > 0",
     "legendFormat": "{{ instance }} IN"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{device=~\"eth.*|enp.*\", cluster=~\"$cluster\"}[$__rate_interval]) * -1 < 0",
     "legendFormat": "{{ instance }} OUT"
    },
    {
     "expr": "irate(ifHCInOctets{cluster=~\"$cluster\"}[$__rate_interval]) > 0",
     "legendFormat": "In - {{ifName}}"
    },
    {
     "expr": "-irate(ifHCOutOctets{cluster=~\"$cluster\"}[$__rate_interval]) < 0",
     "legendFormat": "Out - {{ifName}}"
    }
   ]
  },
  {
   "title": "Global Success Rate (non-5xx responses)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(istio_requests_total{reporter=\"source\", response_code!~\"5.*\", cluster=~\"$cluster\"}[1m])) / sum(rate(istio_requests_total{reporter=\"source\",cluster=~\"$cluster\"}[1m]))"
    }
   ]
  },
  {
   "title": "Global mesh requests per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 2, "y": 12 },
   "targets": [
    {
     "expr": "round(\n    sort_desc(\n        sum by (\n            destination_service_name\n        ) (\n            irate(\n                istio_requests_total{reporter=\"source\", cluster=~\"$cluster\"}[$__rate_interval]\n            )\n        )\n    )> 0 , 0.001\n)",
     "legendFormat": "{{ destination_service_name }}"
    }
   ]
  },
  {
   "title": "P99 request duration",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 11, "x": 13, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "(histogram_quantile(0.99, sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"destination\", cluster=~\"$cluster\"}[1m])) by (le)) / 1000) or histogram_quantile(0.99, sum(irate(istio_request_duration_seconds_bucket{reporter=\"destination\", cluster=~\"$cluster\"}[1m])) by (le))",
     "legendFormat": "P90"
    }
   ]
  },
  {
   "title": "authentik Request duration",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 11, "x": 13, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by (view) (rate(django_http_requests_latency_seconds_by_view_method_sum{view!=\"metrics\"}[$__rate_interval]))",
     "legendFormat": "P90 {{ view }}"
    }
   ]
  },
  {
   "title": "Power usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    { "expr": "hass_sensor_power_w", "legendFormat": "{{ friendly_name }}" }
   ]
  },
  {
   "title": "Temperature",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 8, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hass_sensor_temperature_celsius{entity!~\".*nas.*\"}",
     "legendFormat": "{{ friendly_name }}"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "hass_sensor_humidity_percent", "legendFormat": "{{ friendly_name }}" }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(100 - (\n    (\n        node_filesystem_avail_bytes{fstype!=\"rootfs\",fstype!=\"tmpfs\",fstype!=\"efivarfs\",fstype!=\"fuse.fuse-overlayfs\",mountpoint!~\".*boot.*\", device!~\".*cache.*\"} * 100\n    ) / \n    node_filesystem_size_bytes{fstype!=\"rootfs\",fstype!=\"tmpfs\",fstype!=\"efivarfs\",fstype!=\"fuse.fuse-overlayfs\",mountpoint!~\".*boot.*\", device!~\".*cache.*\"}\n)) > 1",
     "legendFormat": "{{ device }}"
    }
   ]
  }
 ]
}