- name: Ensure sure some packages are installed
  ansible.builtin.apt:
    pkg:
      - open-vm-tools
      - vim
      - htop
      - sudo
      - nmap
      - xkb-data # For /usr/share/X11/xkb/symbols/us, to fix console-setup service
    state: present
    update_cache: yes
  register: apt_res
  retries: 5
  until: apt_res is success
# - name: Ensure sure some packages are not installed
#   ansible.builtin.apt:
#     pkg:
#       - snapd
#       - unattended-upgrades # Prevent APT errors in ansible
#     state: absent
#     purge: yes
#   register: apt_res
#   retries: 5
#   until: apt_res is success
