- name: Enable password-less sudo
  ansible.builtin.copy:
    dest: /etc/sudoers.d/beryjuorg-passwordless
    owner: root
    group: root
    mode: 0644
    content: |
      %sudo ALL=(ALL) NOPASSWD: ALL
    validate: 'visudo -cf %s'
- name: Fix console-setup service on ubuntu 20.04
  ansible.builtin.file:
    state: link
    src: /usr/share/X11/xkb/symbols/us
    dest: /usr/share/X11/xkb/symbols/en
  notify: Restart console-setup
- name: Populate service facts
  ansible.builtin.service_facts:
- name: Ensure multipathd doesnt run
  ansible.builtin.service:
    name: multipathd
    state: stopped
    enabled: no
  when: "'multipathd.service' in ansible_facts.services"
- name: Configure systemd-journald max usage
  ansible.builtin.copy:
    src: ./files/journald.conf
    dest: /etc/systemd/journald.conf
    owner: root
    group: root
    mode: 0644
  notify: Restart systemd-journald
- name: SSH CA Trusted keys
  ansible.builtin.get_url:
    url: https://vault.beryju.org/v1/ssh-client-signer/public_key
    dest: /etc/ssh/trusted-user-ca-keys.pem
- name: Configure SSHD
  ansible.builtin.copy:
    dest: /etc/ssh/sshd_config.d/beryjuio-vault-ssh-ca.conf
    owner: root
    group: root
    mode: 0644
    content: |
      TrustedUserCAKeys /etc/ssh/trusted-user-ca-keys.pem
  notify: Restart sshd
