- name: User jens
  ansible.builtin.user:
    name: jens
    shell: /bin/bash
- name: User jens | default key
  ansible.posix.authorized_key:
    user: jens
    key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC+kSfa9FWWsLxzqkojz28w7xu6PntQd09+1fACTkHOI+9opduAGNJx3+0FbEiOA309HRRyeodpBe6lmzFluMb3ZrvI+r1uwOC8G+O1eiO0+CG28wGTqa/Ww6KaqdEog9EgAIpHZvewwte4t4UBs3BYjF9vf+QpjdtD3zXaKEPsVledUlFQLLiEWW1uTGHBbbPdxKqPtyurEAvoorMKtqB/+NfskkqJoJzZj/M+qHE5Ga5izaUNt11gx4C+AM7RxHYHUuXEo7cOJFfDsJFSbEgCJe947pC7WBAdKXt1yF0i78H4wD19byI4i9+G2ZGHU/wLLU+VfKWGCv5k5thUfMLt" # noqa 204
- name: User jens | new key
  ansible.posix.authorized_key:
    user: jens
    key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDdKEwJwQA8pazibRc+X6Z0QzuPDZz8goUU1OBF2TIzzS86MqEJ22Rwo/51mhKdpALIszOI3x/qX3QiyBtdQU3qbC+XxyxxINXLwziksd/g8JgaTg04N5f/wOw5U/N5WNV2N0kkMxaychJdO5B2NX52hY+Mr+GNNJJKvBxsBRx7jGq+0KsZdCO1vRKXTb7yHSdQlThQDKW2IpHhw/q39Y8BzO2rnV2Zz6KSC8MrCM6BH7MBAWJyLLMuFUJPY/jJa9G6jkCYY51iUGxp5RuMuJQTsnzFSzGfjh2MWgVePBPvIyy/65DPjpRLgMJ7VRKNHkW03YVYS6TJxltGp9PrcQ1e/ksncKzrDTcQX1xcl1vliwmstODFZQLgou+NHJUWL8cc0tsjUzSXgVEzQuSQmfdiB3yhqczZSsA2c9J+tGL7u3KhSaQ9IGQSlPVRnOEOhvhDxa4lGohEaQyW9iwXi1PffkBO4KPLiXCX04a+LfQeGLfm9/arh0xljmAmtEu2eUk= jens-mbp-2021" # noqa 204
- name: User ansible
  ansible.builtin.user:
    name: ansible
    groups:
      - sudo
    shell: /bin/bash
- name: User ansible | authorized_key
  ansible.posix.authorized_key:
    user: ansible
    exclusive: true
    key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDV41SzWt2fDMVYy+WboUetvCEDyQVcEQGyMTIIUenB+Va/xEGrT+ncCS+abnE6vh65no2sipWk6jEQTodiizmYshbWaVTXJrGrWrGAWyKMmpG13otgarleNw/iUYxjRx9cZ75an07KyV2oT2EWiegs53NYJoAa5X1/M56rBg5IEDmqvrr78BhVD13S4RIEZG8su8xdZGe/dv736FVcET1JisJR9AQEzkITrEwxKHh0eWdtG0brdkH6JsGSGSdSj7oBBuOgfFo/wCiKEAzIuUNdITgcOFXh8zQYEZmNo1+Z2W3/ENHyEjK3cPBJlMf3n7qeVs4SWG/qBRBn1rsZuTETKVJ2bQ3RE/GkKoyIXjc5ft3x8dJg4FG/mYO71GsLuc+jJF2jp0q1WeNZfZXJBRiarskazIcVRox+Cv9tc+IpzeEUTo63t8QI+4yfiR7pLp0nr4SWhOVHiUuDp8BJ0G9MI3O//I6B6i8mVt7fxtYXt0VJficpMAl6KwbdoARR9zU= ansible" # noqa 204
- name: Delete vagrant
  ansible.builtin.user:
    name: vagrant
    state: absent
