- name: Restart console-setup
  ansible.builtin.service:
    name: console-setup
    state: restarted
- name: Restart systemd-journald
  ansible.builtin.service:
    name: systemd-journald
    state: restarted
- name: Restart sshd
  ansible.builtin.service:
    name: sshd
    state: restarted
- name: Refresh MOTD cache
  ansible.builtin.shell:
    cmd: run-parts /etc/update-motd.d > /dev/null
  register: _motd_refresh
  changed_when: false
  failed_when: _motd_refresh.rc != 0
