version: "3"

services:
  mc:
    restart: always
    image: itzg/minecraft-server:java17
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
      INIT_MEMORY: 1G
      MAX_MEMORY: 7G
    volumes:
      - /srv/mc:/data
  mc_exporter:
    restart: always
    image: ghcr.io/dirien/minecraft-exporter:0.12.0-amd64
    ports:
      - 10.120.0.59:9150:9150
    volumes:
      - /srv/mc:/data:ro
    command:
      - --mc.rcon-address=mc:25575
      - --mc.rcon-password=<%= $services_minecraft.unwrap[data][rcon] %>
      - --mc.world=/data/world
