export ARA_API_CLIENT="http"
export ARA_API_SERVER="https://ara.beryjuio-home.k8s.beryju.io"
export ANSIBLE_CALLBACK_PLUGINS=$(uv run python3 -m ara.setup.callback_plugins)
alias ap="ansible-playbook --diff"
source /workspaces/infrastructure/.venv/bin/activate
export ANSIBLE_REMOTE_USER="ansible"
export ANSIBLE_PRIVATE_KEY_FILE=/workspaces/infrastructure/ansible.key
export ANSIBLE_HOST_KEY_CHECKING="false"
