version: '3'
services:
  mongo:
    image: library/mongo:4.2
    volumes:
      - mongo_data:/data/db
    networks:
      - graylog
    restart: always
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    volumes:
      - es_data:/usr/share/elasticsearch/data
    environment:
      http.host: "0.0.0.0"
      transport.host: "localhost"
      network.host: "0.0.0.0"
      cluster.routing.allocation.disk.threshold_enabled: "false"
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - graylog
    restart: always
  graylog:
    restart: always
    image: graylog/graylog:4.2.0
    volumes:
      - graylog_journal:/usr/share/graylog/data/journal
      - ./map:/etc/graylog/server/map
    environment:
      GRAYLOG_PASSWORD_SECRET: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=kv/data/services/graylog:password_secret') }}"
      GRAYLOG_ROOT_PASSWORD_SHA2: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=kv/data/services/graylog:root_password') }}"
      GRAYLOG_HTTP_EXTERNAL_URI: "https://log.beryju.org/"
      GRAYLOG_TRUSTED_PROXIES: "10.120.0.0/24"
      GRAYLOG_PROMETHEUS_EXPORTER_ENABLED: "true"
      GRAYLOG_PROMETHEUS_EXPORTER_BIND_ADDRESS: "0.0.0.0:9001"
    networks:
      - graylog
    depends_on:
      - mongo
      - elasticsearch
    ports:
      # Graylog web interface and REST API
      - 4180:9000
      - 9001:9001
      # vyos syslog tcp
      - 514:10000
      - 10001-10100:10001-10100
      - 10001-10100:10001-10100/udp


networks:
  graylog:
    driver: bridge

volumes:
  mongo_data:
    driver: local
  es_data:
    driver: local
  graylog_journal:
    driver: local
