version: "3"

services:
  mc:
    image: itzg/minecraft-server:java17
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
      INIT_MEMORY: 1G
      MAX_MEMORY: 3.5G
    volumes:
      - /srv/mc:/data
