version: "3.5"

services:
  check_mk:
    image: registry.beryju.org/check-mk-enterprise:2.0.0p17
    restart: always
    ports:
      - 5000:5000
    volumes:
      - /srv/checkmk:/omd/sites
    container_name: monitoring
    tmpfs: /opt/omd/sites/cmk/tmp:uid=1000,gid=1000
    ulimits:
      nofile: 1024
