version: '3.7'

services:
  adc_exporter_1:
    image: quay.io/citrix/citrix-adc-metrics-exporter:1.4.7
    volumes:
      - ./config.yaml:/exporter/config.yaml
    ports:
      - 8890:8888
    command:
      - --target-nsip=adc1.prod.beryju.org
      - --port=8888
    environment:
      NS_USER: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=kv/data/citrix/adc:username') }}"
      NS_PASSWORD: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=kv/data/citrix/adc:password') }}"
  adc_exporter_2:
    image: quay.io/citrix/citrix-adc-metrics-exporter:1.4.7
    volumes:
      - ./config.yaml:/exporter/config.yaml
    ports:
      - 8891:8888
    command:
      - --target-nsip=adc2.prod.beryju.org
      - --port=8888
    environment:
      NS_USER: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=kv/data/citrix/adc:username') }}"
      NS_PASSWORD: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=kv/data/citrix/adc:password') }}"
