- hosts: localhost
  become: false
  vars:
    vcenter: &vcenter
      hostname: "vc1.prod.beryju.org"
      username: '{{ lookup("community.hashi_vault.hashi_vault", "secret=kv/data/vsphere/local/administrator:username") }}'
      password: '{{ lookup("community.hashi_vault.hashi_vault", "secret=kv/data/vsphere/local/administrator:password") }}'
      validate_certs: False
  tasks:
    - name: Add Veeam Role
      community.vmware.vmware_local_role_manager:
        local_role_name: Veeam
        local_privilege_ids:
          - "Cryptographer.Access"
          - "Cryptographer.AddDisk"
          - "Cryptographer.Encrypt"
          - "Cryptographer.EncryptNew"
          - "Cryptographer.Migrate"
          - "DVPortgroup.Create"
          - "DVPortgroup.Delete"
          - "DVPortgroup.Modify"
          - "Datastore.AllocateSpace"
          - "Datastore.Browse"
          - "Datastore.Config"
          - "Datastore.DeleteFile"
          - "Datastore.FileManagement"
          - "Extension.Register"
          - "Extension.Unregister"
          - "Folder.Create"
          - "Folder.Delete"
          - "Global.DisableMethods"
          - "Global.EnableMethods"
          - "Global.Licenses"
          - "Global.LogEvent"
          - "Global.ManageCustomFields"
          - "Global.SetCustomField"
          - "Global.Settings"
          - "Host.Config.AdvancedConfig"
          - "Host.Config.Maintenance"
          - "Host.Config.Network"
          - "Host.Config.Patch"
          - "Host.Config.Storage"
          - "InventoryService.Tagging.AttachTag"
          - "Network.Assign"
          - "Network.Config"
          - "Resource.AssignVMToPool"
          - "Resource.ColdMigrate"
          - "Resource.CreatePool"
          - "Resource.DeletePool"
          - "Resource.HotMigrate"
          - "StoragePod.Config"
          - "StorageProfile.Update"
          - "StorageProfile.View"
          - "System.Anonymous"
          - "System.Read"
          - "System.View"
          - "VApp.AssignResourcePool"
          - "VApp.AssignVM"
          - "VApp.Unregister"
          - "VirtualMachine.Config.AddExistingDisk"
          - "VirtualMachine.Config.AddNewDisk"
          - "VirtualMachine.Config.AddRemoveDevice"
          - "VirtualMachine.Config.AdvancedConfig"
          - "VirtualMachine.Config.Annotation"
          - "VirtualMachine.Config.ChangeTracking"
          - "VirtualMachine.Config.DiskExtend"
          - "VirtualMachine.Config.DiskLease"
          - "VirtualMachine.Config.EditDevice"
          - "VirtualMachine.Config.RawDevice"
          - "VirtualMachine.Config.RemoveDisk"
          - "VirtualMachine.Config.Rename"
          - "VirtualMachine.Config.Resource"
          - "VirtualMachine.Config.Settings"
          - "VirtualMachine.GuestOperations.Execute"
          - "VirtualMachine.GuestOperations.Modify"
          - "VirtualMachine.GuestOperations.Query"
          - "VirtualMachine.Interact.ConsoleInteract"
          - "VirtualMachine.Interact.DeviceConnection"
          - "VirtualMachine.Interact.GuestControl"
          - "VirtualMachine.Interact.PowerOff"
          - "VirtualMachine.Interact.PowerOn"
          - "VirtualMachine.Interact.SetCDMedia"
          - "VirtualMachine.Interact.SetFloppyMedia"
          - "VirtualMachine.Interact.Suspend"
          - "VirtualMachine.Inventory.Create"
          - "VirtualMachine.Inventory.CreateFromExisting"
          - "VirtualMachine.Inventory.Delete"
          - "VirtualMachine.Inventory.Register"
          - "VirtualMachine.Inventory.Unregister"
          - "VirtualMachine.Provisioning.DiskRandomAccess"
          - "VirtualMachine.Provisioning.DiskRandomRead"
          - "VirtualMachine.Provisioning.GetVmFiles"
          - "VirtualMachine.Provisioning.MarkAsTemplate"
          - "VirtualMachine.Provisioning.MarkAsVM"
          - "VirtualMachine.Provisioning.PutVmFiles"
          - "VirtualMachine.State.CreateSnapshot"
          - "VirtualMachine.State.RemoveSnapshot"
          - "VirtualMachine.State.RenameSnapshot"
          - "VirtualMachine.State.RevertToSnapshot"
        state: present
        <<: *vcenter
