global:
  scrape_interval: 30s
  scrape_timeout: 10s
  evaluation_interval: 1m

rule_files:
- /etc/prometheus/rules/*.yaml

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093

scrape_configs:
  - job_name: "vmware/node-exporter"
    basic_auth:
      username: 'prometheus'
      password: '{{ lookup("community.hashi_vault.hashi_vault", "secret=kv/data/services/prometheus/node_exporter:prometheus") }}'
    scheme: https
    tls_config:
      insecure_skip_verify: true
    file_sd_configs:
      - files:
          - /opt/config/vmware-filesd/vmware-filesd.json
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
      - source_labels: [__address__]
        target_label: __address__
        replacement: "${1}:9100"

  - job_name: static_nodes
    basic_auth:
      username: 'prometheus'
      password: '{{ lookup("community.hashi_vault.hashi_vault", "secret=kv/data/services/prometheus/node_exporter:prometheus") }}'
    scheme: https
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets:
          - 'backup-s3.beryju.org:9100'
          - 'sentry1.prod.beryju.org:9100'

  - job_name: imagik_tig
    static_configs:
      - targets:
          - '10.51.110.26:9300'
  - job_name: harvest
    static_configs:
      - targets:
          - 'mon1.prod.beryju.org:12990'
          - 'mon1.prod.beryju.org:12991'
          - 'mon1.prod.beryju.org:12992'
          - 'mon1.prod.beryju.org:12993'
  - job_name: graphite
    static_configs:
      - targets:
          - 'mon1.prod.beryju.org:9108'
  - job_name: alertmanager
    static_configs:
      - targets:
          - 'mon1.prod.beryju.org:9093'
  - job_name: loki
    static_configs:
      - targets:
          - 'log1.prod.beryju.org:3100'
  - job_name: loki_promtail
    static_configs:
      - targets:
          - 'log1.prod.beryju.org:9080'
  - job_name: unifi
    static_configs:
      - targets:
          - 'unifi1.prod.beryju.org:9130'
  - job_name: vault
    metrics_path: /v1/sys/metrics
    params:
      format:
      - prometheus
    bearer_token: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=kv/data/services/vault:monitoring_token') }}"
    scheme: https
    static_configs:
      - targets:
          - 'vault.beryju.org:443'
  - job_name: "hass"
    metrics_path: "/api/prometheus"
    bearer_token: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=kv/data/services/hass/monitoring:token') }}"
    scheme: http
    static_configs:
      - targets: ["hass1.prod.beryju.org:8123"]
