version: "3.5"

networks:
  traefik:
    external:
      name: traefik

services:
  traefik:
    image: traefik:1.7-alpine
    container_name: traefik
    command:
      - "--logLevel=INFO"
      - "--defaultentrypoints=http,https"
      - "--entryPoints=Name:http Address::80 Redirect.EntryPoint:https"
      - "--entryPoints=Name:https Address::443 TLS"
      - "--docker"
      - "--docker.exposedbydefault=false"
      - "--docker.domain=beryju.org"
      - "--acme=true"
      - "--acme.acmelogging=true"
      - "--acme.email=jens@beryju.org"
      - "--acme.storage=acme.json"
      - "--acme.entryPoint=https"
      - "--acme.onhostrule=true"
      - "--acme.httpchallenge=true"
      - "--acme.httpchallenge.entrypoint=http"
    ports:
      - "194.56.224.172:80:80"
      - "194.56.224.172:443:443"
    networks:
      - traefik
    volumes:
      - "/srv/traefik/acme.json:/acme.json"
      - "/var/run/docker.sock:/var/run/docker.sock"
    restart: always

  check_mk:
    image: docker.beryju.org/k8s/check-mk-enterprise:2.0.0p3
    restart: always
    ports:
      - 10.120.0.57:5000:5000
    networks:
      - traefik
    volumes:
      - /srv/checkmk:/omd/sites
    container_name: monitoring
    tmpfs: /opt/omd/sites/cmk/tmp:uid=1000,gid=1000
    ulimits:
      nofile: 1024
    labels:
      - "traefik.enable=true"
      - "traefik.port=5000"
      - "traefik.frontend.rule=Host:monitoring.beryju.org"
      - "traefik.docker.network=traefik"
