version: "3.5"

services:
  grafana:
    image: grafana/grafana:8.0.5
    container_name: grafana
    volumes:
      - /srv/grafana:/var/lib/grafana
    ports:
      - 3000:3000
    environment:
      GF_SERVER_DOMAIN: "grafana.infra.beryju.org"
      GF_SERVER_ROOT_URL: "https://grafana.infra.beryju.org/"
      GF_INSTALL_PLUGINS: "vonage-status-panel,grafana-polystat-panel,jdbranham-diagram-panel"
      GF_AUTH_GENERIC_OAUTH_ENABLED: "true"
      GF_AUTH_GENERIC_OAUTH_NAME: "authentik"
      GF_AUTH_GENERIC_OAUTH_CLIENT_ID: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=kv/data/services/grafana:oauth_client_id') }}"
      GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=kv/data/services/grafana:oauth_client_secret') }}"
      GF_AUTH_GENERIC_OAUTH_SCOPES: "openid profile email"
      GF_AUTH_GENERIC_OAUTH_AUTH_URL: "https://id.beryju.org/application/o/authorize/"
      GF_AUTH_GENERIC_OAUTH_TOKEN_URL: "https://id.beryju.org/application/o/token/"
      GF_AUTH_GENERIC_OAUTH_API_URL: "https://id.beryju.org/application/o/userinfo/"
      GF_AUTH_SIGNOUT_REDIRECT_URL: "https://id.beryju.org/application/o/grafana/end-session/"
      # Optionally enable auto-login
      GF_AUTH_OAUTH_AUTO_LOGIN: "true"
