version: '3.7'

services:
  prometheus:
    image: prom/prometheus:v2.29.2
    command:
      - --web.enable-lifecycle
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --enable-feature=remote-write-receiver
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./rules:/etc/prometheus/rules
      - /srv/prometheus-data:/prometheus
    ports:
      - 9090:9090
    restart: always
  graphite_exporter:
    image: quay.io/prometheus/graphite-exporter:latest
    command:
      - --graphite.mapping-config=/tmp/graphite.yaml
    volumes:
      - ./graphite.yaml:/tmp/graphite.yaml
    ports:
      - 9108:9108
      - 9109:9109
      - 9109:9109/udp
  alertmanager:
    image: prom/alertmanager
    volumes:
      - ./alertmanager.yml:/etc/prometheus/alertmanager.yml
      - /srv/prom-alertmanager/:/data
    command:
      - '--config.file=/etc/prometheus/alertmanager.yml'
      - '--storage.path=/data'
    ports:
      - 9093:9093
    restart: always
