version: "3.5"

networks:
  traefik:
    external:
      name: traefik

services:
  grafana:
    image: grafana/grafana:8.0.1
    container_name: grafana
    volumes:
      - /srv/grafana:/var/lib/grafana
    ports:
      - 10.120.0.57:3000:3000
    networks:
      - traefik
    environment:
      GF_SERVER_DOMAIN: "monitoring.beryju.org"
      GF_INSTALL_PLUGINS: "vonage-status-panel,grafana-polystat-panel,jdbranham-diagram-panel"
      GF_SERVER_ROOT_URL: "https://monitoring.beryju.org/grafana/"
      GF_AUTH_GENERIC_OAUTH_ENABLED: "true"
      GF_AUTH_GENERIC_OAUTH_NAME: "authentik"
      GF_AUTH_GENERIC_OAUTH_CLIENT_ID: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=kv/data/services/grafana:oauth_client_id') }}"
      GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=kv/data/services/grafana:oauth_client_secret') }}"
      GF_AUTH_GENERIC_OAUTH_SCOPES: "openid profile email"
      GF_AUTH_GENERIC_OAUTH_AUTH_URL: "https://id.beryju.org/application/o/authorize/"
      GF_AUTH_GENERIC_OAUTH_TOKEN_URL: "https://id.beryju.org/application/o/token/"
      GF_AUTH_GENERIC_OAUTH_API_URL: "https://id.beryju.org/application/o/userinfo/"
      GF_AUTH_SIGNOUT_REDIRECT_URL: "https://id.beryju.org/application/o/grafana/end-session/"
      # Optionally enable auto-login
      GF_AUTH_OAUTH_AUTO_LOGIN: "true"
    labels:
      traefik.enable: "true"
      traefik.http.routers.grafana.entrypoints: https
      traefik.http.routers.grafana.tls: "true"
      traefik.http.routers.grafana.tls.certresolver: myresolver
      traefik.http.routers.grafana.rule: Host(`monitoring.beryju.org`) && PathPrefix(`/grafana`)
      traefik.http.routers.grafana.middlewares: grafana-stripprefix
      traefik.http.middlewares.grafana-stripprefix.stripprefix.prefixes: /grafana
      traefik.docker.network: traefik
