version: "3.7"
services:
  vault:
    image: vault:1.7.3
    ports:
      - "10.120.0.69:8200:8200"
    volumes:
      - /srv/vault/data:/vault/data:rw
      - /srv/vault/files:/vault/file:rw
      - /srv/vault/config:/vault/config:rw
    cap_add:
      - IPC_LOCK
    entrypoint: vault server -config=/vault/config/vault.hcl
