- name: Generate newaliases
  ansible.builtin.command: newaliases

- name: Restart postfix
  ansible.builtin.service:
    name: postfix
    state: restarted

- name: Generate relay_passwd
  ansible.builtin.command: postmap hash:/etc/postfix/relay_passwd
