nfs_exports:
  - path: /bigpool/media
    client: 10.120.20.0/24
    opts: ro,async,no_subtree_check,no_root_squash
  - path: /bigpool/media
    client: k8s-defr-c1.lab.beryju.org
  - path: /bigpool/media
    client: k8s-defr-w1.lab.beryju.org
  - path: /bigpool/media
    client: k8s-defr-w2.lab.beryju.org
  - path: /bigpool/media
    client: plex1.prod.beryju.org
