- hosts: localhost
  vars:
    gitlab_connection: &gitlab_connection
      api_url: "https://code.beryju.org"
      api_token: '{{ lookup("community.hashi_vault.hashi_vault", "secret=kv/data/awx/git-backup:gitlab-token") }}'
    tmp_path: /tmp/backup
    backup_group: "backups"
    projects:
      - src: BeryJu/korb
        dst: korb
      - src: BeryJu/k8s
        dst: k8s
      - src: BeryJu/infrastructure
        dst: infrastructure
      - src: goauthentik/authentik
        dst: authentik
      - src: BeryJu/beryju.org
        dst: beryju.org
      - src: BeryJu/hass-auth-header
        dst: hass-auth-header
      - src: BeryJu/kube-dhcp
        dst: kube-dhcp
      - src: BeryJu/hue-link
        dst: hue-link
      - src: BeryJu/imagik
        dst: imagik
      - src: BeryJu/oauth1-test-server
        dst: oauth1-test-server
      - src: BeryJu/oidc-test-client
        dst: oidc-test-client
      - src: BeryJu/saml-test-sp
        dst: saml-test-sp
      - src: BeryJu/acme-for-appliances
        dst: acme-for-appliances
      - src: BeryJu/hass-ticktick
        dst: hass-ticktick
  tasks:
    - name: Dst | Ensure gitlab project exists
      community.general.gitlab_project:
        name: "{{ item.dst }}"
        group: "{{ backup_group }}"
        <<: *gitlab_connection
      loop: "{{ projects }}"
    - name: Dst | Remove protected branches (master)
      community.general.gitlab_protected_branch:
        project: "{{ backup_group }}/{{ item.dst }}"
        name: 'master'
        state: absent
        <<: *gitlab_connection
      loop: "{{ projects }}"
    - name: Dst | Remove protected branches (main)
      community.general.gitlab_protected_branch:
        project: "{{ backup_group }}/{{ item.dst }}"
        name: 'main'
        state: absent
        <<: *gitlab_connection
      loop: "{{ projects }}"
    - name: Src | get source
      ansible.builtin.git:
        repo: 'https://github.com/{{ item.src }}.git'
        dest: "{{ tmp_path }}/{{ item.dst }}"
        force: true
      loop: "{{ projects }}"
    - name: Src | full fetch
      command: git -C '{{ tmp_path }}/{{ item.dst }}' pull --all
      loop: "{{ projects }}"
    - name: Src | add backup remote
      command: git -C '{{ tmp_path }}/{{ item.dst }}' remote add backup '{{ gitlab_connection.api_url }}/{{ backup_group }}/{{ item.dst }}'
      loop: "{{ projects }}"
    - name: Dst | push
      command: git -C '{{ tmp_path }}/{{ item.dst }}' push --repo 'https://git:{{ gitlab_connection.api_token }}@code.beryju.org/{{ backup_group }}/{{ item.dst }}' --force  # noqa 204
      loop: "{{ projects }}"
    - name: Local | cleanup
      file:
        state: absent
        path: "{{ tmp_path }}/{{ item.dst }}"
      loop: "{{ projects }}"
