- import_playbook: ../bootstrap.yaml
- hosts: docker
  become: true
  tasks:
    - name: Clean Docker Images (all)
      # noqa 301
      ansible.builtin.command: docker image prune -a -f
    - name: Clean Docker images
      community.docker.docker_prune:
        containers: false
        builder_cache: true
        images: true
        images_filters:
          dangling: false
- hosts: kube
  become: true
  tasks:
    - name: Clean Containerd Images (all)
      # noqa 301
      ansible.builtin.command: crictl rmi --prune
