- hosts: all
  become: true
  tasks:
#    - name: config
#      command: /opt/puppetlabs/puppet/bin/puppet config set server puppet.infra.beryju.org --section main
    - name: config
      command: /opt/puppetlabs/puppet/bin/puppet config set certname {{ inventory_hostname }} --section main
    - name: run
      command: /opt/puppetlabs/puppet/bin/puppet agent -t
