- import_playbook: ../pre_run.yaml
- hosts: sentry1.prod.beryju.org
  become: true
  tasks:
    - name: Run sentry inbuilt cleanup
      community.docker.docker_container_exec:
        container: sentry_onpremise_worker_1
        command: sentry cleanup --days 30
      failed_when: false
    - name: Vacuum database (complete, first pass)
      community.docker.docker_container_exec:
        container: sentry_onpremise_postgres_1
        command: vacuumdb -U sentry -d sentry -v -f --analyze
    - name: Vacuum nodestore_node (first pass)
      community.docker.docker_container_exec:
        container: sentry_onpremise_postgres_1
        command: psql -U sentry -c "vacuum public.nodestore_node;"
    - name: Vacuum nodestore_node (second pass)
      community.docker.docker_container_exec:
        container: sentry_onpremise_postgres_1
        command: psql -U sentry -c "vacuum full public.nodestore_node;"
- import_playbook: ../post_run.yaml
