- hosts: sentry1.prod.beryju.org
  become: true
  tasks:
    - name: Run sentry inbuilt cleanup
      community.docker.docker_container_exec:
        container: sentry_onpremise_worker_1
        command: sentry cleanup --days 30
      ignore_errors: yes
    - name: Vacuum database (complete, first pass)
      community.docker.docker_container_exec:
        container: sentry_onpremise_postgres_1
        command: vacuumdb -U sentry -d sentry -v -f --analyze
    - name: Run pg-repack
      community.docker.docker_container_exec:
        container: sentry_onpremise_postgres_1
        command: apt update && apt install -y --no-install-recommends postgresql-9.6-repack && su postgres -c 'pg_repack -E info -t nodestore_node'
