- import_playbook: ../bootstrap.yaml
- hosts: sentry1.prod.beryju.io
  become: true
  vars:
    bucket_name: sentry-backups
    sentry_dir: "/home/jens/self-hosted"
    filename: "sentry_{{ ansible_date_time.date }}.json"
    s3_connection: &s3_connection
      endpoint_url: "https://s3.beryju.io/"
      access_key: '{{ lookup("community.hashi_vault.hashi_vault", "secret=kv/data/services/minio/main:username") }}'
      secret_key: '{{ lookup("community.hashi_vault.hashi_vault", "secret=kv/data/services/minio/main:password") }}'
  tasks:
    - name: Ensure S3 bucket exists
      delegate_to: localhost
      become: false
      amazon.aws.s3_bucket:
        name: "{{ bucket_name }}"
        state: present
        <<: *s3_connection
    - name: Create backups subdirectory
      ansible.builtin.file:
        state: directory
        path: "{{ sentry_dir }}/sentry/backups"
    - name: Run export
      community.docker.docker_container_exec:
        container: sentry-self-hosted-web-1
        command: "sentry export global /etc/sentry/backups/{{ filename }}"
    - name: Sync sentry backups dir
      community.aws.s3_sync:
        bucket: "{{ bucket_name }}"
        file_root: "{{ sentry_dir }}/sentry/backups"
        <<: *s3_connection
