- import_playbook: ../bootstrap.yaml
- hosts: all
  become: true

  strategy: free # noqa: run-once[play]
  gather_facts: false
  tasks:
    - name: Apt | update cache
      ansible.builtin.apt:
        update_cache: true
    - name: Apt | full-upgrade
      ansible.builtin.apt:
        upgrade: full
      register: apt_res
      retries: 5
      until: apt_res is success
    - name: Apt | autoremove
      ansible.builtin.apt:
        autoremove: true
      register: apt_res
      retries: 5
      until: apt_res is success
    - name: Clean apt cache
      # noqa 301 303
      ansible.builtin.command: apt-get clean
      register: result
      retries: 5
      until: result.rc == 0
    - name: Remove prometheus cache
      ansible.builtin.file:
        path: /var/lib/prometheus/node-exporter/apt.prom
        state: absent
