- hosts: all
  become: true
  strategy: free
  tasks:
    - name: apt | update cache
      apt:
        update_cache: yes
    - name: apt | full-upgrade
      apt:
        upgrade: full
      register: apt_res
      retries: 5
      until: apt_res is success
    - name: apt | autoremove
      apt:
        autoremove: yes
      register: apt_res
      retries: 5
      until: apt_res is success
    - name: Clean apt cache
      # noqa 301 303
      command: apt-get clean
      register: result
      retries: 5
      until: result.rc == 0
    - name: Remove prometheus cache
      file:
        path: /var/lib/prometheus/node-exporter/apt.prom
        state: absent
