- name: create stack directory
  file:
    state: directory
    path: "{{ docker_compose_stacks_path }}/{{ stack.name }}"
    owner: root
    group: root
    mode: 0755

# Stack file
- name: copy stack file
  copy:
    src: "{{ stack.file }}"
    dest: "{{ docker_compose_stacks_path }}/{{ stack.name }}/docker-compose.yml"
    owner: root
    group: root
    mode: 0644
  when: "stack.file is defined"

# Stack template
- name: copy template stack file
  template:
    src: "{{ stack.template }}"
    dest: "{{ docker_compose_stacks_path }}/{{ stack.name }}/docker-compose.yml"
    owner: root
    group: root
    mode: 0644
  when: "stack.template is defined"

# Stack repo
- name: clone stack repo
  git:
    repo: "{{ stack.repo }}"
    dest: "{{ docker_compose_stacks_path }}/{{ stack.name }}/"
    version: "{{ stack.branch | default('master') }}"
  when: "stack.repo is defined"

# Stack files
- name: Copy additional stack files
  template:
    src: "{{ file.src }}"
    dest: "{{ docker_compose_stacks_path }}/{{ stack.name }}/{{ file.dest }}"
    mode: "{{ file.mode|default('0644') }}"
    owner: "{{ file.owner|default('root') }}"
    group: "{{ file.group|default('root') }}"
  loop: "{{ stack.files }}"
  loop_control:
    loop_var: file
  when: "stack.files is defined"
  notify: restart stack

- name: start stack
  docker_compose:
    project_src: "{{ docker_compose_stacks_path }}/{{ stack.name }}"
    remove_orphans: yes
    pull: yes
