- name: Restart containerd
  ansible.builtin.service:
    name: containerd
    state: restarted
- name: Apt update
  ansible.builtin.apt:
    update_cache: true
- name: Update kubeadm config
  ansible.builtin.command: kubeadm init phase upload-config kubeadm --config /etc/kubernetes/kubeadmin-config.yml
  changed_when: true
