name: docker-build-ee

on:
  push:
    branches: [ master ]
    paths: [ ee/** ]
  schedule:
    - cron: '0 5 * * *'
  workflow_dispatch:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push Docker images
      uses: docker/build-push-action@v2.8.0
      with:
        context: ee/
        tags: ghcr.io/beryju/awx-ee:latest
        push: ${{ github.ref == 'refs/heads/master' }}
