name: docker-build-workstation

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to BeryJu.org harbor Registry
      uses: docker/login-action@v1
      with:
        registry: beryju.org
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Get current timestamp
      id: time
      run: echo "::set-output name=time::$(date +'%s')"
    - name: Build and push Docker images
      uses: docker/build-push-action@v2.6.1
      with:
        context: workstation/
        tags: |
          beryju.org/jens/workstation:latest,
          beryju.org/jens/workstation:auto-${{ steps.time.outputs.time }}
        push: ${{ github.ref == 'refs/heads/master' }}
        build-args: |
          HOST_RSA_KEY=${{ secrets.HOST_RSA_KEY }}
          HOST_ECDSA_KEY=${{ secrets.HOST_ECDSA_KEY }}
