name: docker-build-frr-exporter

on:
  push:
    branches: [ master ]
    paths: [ images/frr-exporter/** ]
  schedule:
    - cron: '0 5 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Get current timestamp
      id: time
      run: echo "::set-output name=time::$(date +'%s')"
    - name: Build and push Docker images
      uses: docker/build-push-action@v3.1.1
      with:
        context: images/frr-exporter/
        tags: |
          ghcr.io/beryju/frr-exporter:latest,
          ghcr.io/beryju/frr-exporter:auto-${{ steps.time.outputs.time }}
        push: ${{ github.ref == 'refs/heads/master' }}
