name: docker-build-workstation

on:
  push:
    branches: [ main ]
    paths: [ images/workstation/** ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Get current timestamp
      id: time
      run: echo "time=$(date +'%s')" >> $GITHUB_OUTPUT
    - name: Build and push Docker images
      uses: docker/build-push-action@v6.5.0
      with:
        context: images/workstation/
        tags: |
          ghcr.io/beryju/workstation:latest,
          ghcr.io/beryju/workstation:auto-${{ steps.time.outputs.time }}
        push: ${{ github.ref == 'refs/heads/main' }}
