---
name: Run ansible (puppet-update)

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  ansible:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 1
    - name: Run playbook
      uses: ./.github/actions/run-ansible
      with:
        playbook: actions/puppet-update.yaml
