---
name: Run ansible (backup)

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'

permissions:
  contents: read
  id-token: write

jobs:
  ansible:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 1
    - name: Run playbook
      uses: ./.github/actions/run-ansible
      with:
        playbook: actions/backup.yaml
