---
name: Terraform upgrade

on:
  workflow_dispatch:
  push:
    branches:
    - master
  pull_request:

jobs:
  ansible:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - uses: hashicorp/setup-terraform@v1
    - run: terraform init -upgrade
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: update-tf-lock
        commit-message: Update terraform lock
        title: Update terraform lock
        delete-branch: true
        signoff: true
